### ISSUE TITLE
radio button options misunderstanding in usage

### ISSUE THREAD

**Issue by parmonov98** [bastinald/ui#10]
TypeError
Illuminate\Support\Arr::isAssoc(): Argument #1 ($array) must be of type array, string given, called in /var/www/webdashboard.test/storage/framework/views/9d465923f39b268503f96b3b64bf195c5b6b59ca.php on line 22 (View: /var/www/webdashboard.test/resources/views/vendor/ui/components/radio.blade.php)

used in save.blade.php
<x-ui::radio :label="__('Роль')" options="['supervisor', 'manager']"  model="role"/>

role exists in users table. default value is manager

What to send ? passing array in options.

**Comment by bastinald** [comment]
You're missing a colon before options.
