### ISSUE TITLE
new feature needed pass an assoc array property to select component as options, not like a string. 

### ISSUE THREAD

**Issue by parmonov98** [bastinald/ui#14]
<x-ui::select :label="__('Color')" :options="['Red', 'Blue']" model="color"/>

What I want is to pass an assoc array and the select component should parse it automatically

```
$managers = User::where('role', 'manager')->get(['id', 'name']);

$arr = [];
$managers->map(function ($item) use (&$arr){
    $arr[$item->id] = $item->name;
});

$this->managerOptions = $arr;
```

use it in view like this
`<x-ui::select :label="__('Manager')" :options="managerOptions" model="manager_id"/>`

thanks

**Comment by bastinald** [comment]
Pass managerOptions to your view as a variable then use '$managerOptions' for the select options.
