### ISSUE TITLE
Wanted to know which Laravel-Livewire Scaffolding to use

### ISSUE THREAD

**Issue by saudashfaq** [bastinald/ui#15]
Hi @bastinald ,

Your repositories are awesome, welldone.

Please let me know what is the difference between UI, Laravel-Livewire Scaffolding Starter kits (all reps that deal with basic starter kit laravel-livewire), or which I should use for my new project.

Thanks.

**Comment by MACscr** [comment]
That’s completely up to you. I think UX might be the latest? Look at all the different docs and see which one you like.

- Mark

**Comment by saudashfaq** [comment]
> That’s completely up to you. I think UX might be the latest? Look at all the different docs and see which one you like. - Mark
> […](#)
> On Sep 23, 2021, at 4:58 AM, saudashfaq ***@***.***> wrote: ﻿ Hi @bastinald , Your repositories are awesome, welldone. Please let me know what is the difference between UI, Laravel-Livewire Scaffolding Starter kits (all reps that deal with basic starter kit laravel-livewire), or which I should use for my new project. Thanks. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Thanks a lot.
