### ISSUE TITLE
how to get variable from route url in custom?

### ISSUE THREAD

**Issue by parmonov98** [bastinald/ui#17]
![image](https://user-images.githubusercontent.com/24564577/138587169-cfde77d2-a40f-418d-b932-8966a8205451.png)

I get this
![image](https://user-images.githubusercontent.com/24564577/138587180-e4af2eb1-54aa-4de4-90e9-fbc03bfb2ddd.png)

How can I get employee_id assigned to public property id?

**Comment by heyjoe1984** [comment]
public $id;

    public function mount($id) {
        $this->id = $id;
    }
