### ISSUE TITLE
Feature Request: Searchable/Filterable Tables

### ISSUE THREAD

**Issue by MACscr** [bastinald/ui#2]
I really like your coding style and everything appears to be very straightforward to use. Great documentation too. Only thing I have left that i really need is a solid livewire table option for BS5. The only one that I know of is https://github.com/rappasoft/laravel-livewire-tables, which isnt bad, but from what i have seen from your packages so far, yours would be even more flexible and easier to use. Have anything in the works?

**Comment by bastinald** [comment]
Well, I don't really use tables that much anymore. I prefer responsive grids which change based on the viewport.

That being said, I'm considering adding a `ui:crud` command to generate some basic crud scaffolding, which would include a searchable/sortable/filterable index view for model listings.

**Comment by MACscr** [comment]
Obviously doesn’t have to be an actual table, but index pages for CRUD type content. Important for admin panels, which is what I am trying to piece together without having to use actual constrictive panels like Nova or Filament.

- Mark

**Comment by bastinald** [comment]
> Obviously doesn’t have to be an actual table, but index pages for CRUD type content. Important for admin panels, which is what I am trying to piece together without having to use actual constrictive panels like Nova or Filament. - Mark
> […](#)

I'll work on a new `ui:crud` command for this over the weekend :)

It will generate actual flexible code for you so the sky is the limit, just like with everything else in this package.

**Comment by MACscr** [comment]
Awesome! Thank you so much for saving me from all these other messes. Also, I didn’t mind the 40min YouTube video as it was super helpful in getting a good grasp of the framework has available. Thanks again!

- Mark

**Comment by bastinald** [comment]
@MACscr 

I think I'm actually going to make a new package with CRUD in mind.

There are a few things about this package that I feel could have been executed better.

I'll let you know when its done.

**Comment by MACscr** [comment]
lol, ok. Guess I should slow my role tonight on the project? =P

**Comment by bastinald** [comment]
Lol yeah. I'm pretty OCD when it comes to releasing new packages every week. 

But this new one will be better and have more features. Will implement a lot of stuff from this package with more refinements. 

For example right now I'm adding badges to nav items because you currently have no way of doing it aside from straight bootstrap code. Also refining some naming conventions etc.

**Comment by MACscr** [comment]
Don't change it too much. I love how you can easily embed form elements, etc into blade files as that allows tons of control over the layout of the forms versus even the approach you used in the bastinald/laravel-livewire-forms package.

Also, if it means anything, I have a lot of relational data since this is primary going to be for a CRM for a non profit. With that in mind, its important to be able to tie data together on creation, not after. A generic example would be two models with Posts and PostTags. Its important to be able to assign the tags to the post on post creation. Not simply creating the post, then having to assign the tags or other relational data after the fact that most of the admin panel solutions seem to do for some odd reason. Im a stickler for UX and anything that requires extra clicks/steps than necessary is a big negative to me. Zero clue if what you are making has anything to do with any of that, but wanted to though that out there.

Another simple example would be on user creation, assigning a role or roles during the user creation process, not after the user is created.

- Mark

**Comment by bastinald** [comment]
The new package will be admin panel style but still give you full control just like this one does. 

All the existing admin panel packages I've seen for Laravel are either restrictive, clunky, or both.

**Comment by MACscr** [comment]
I am excited to start testing it tomorrow. ;) lol

- Mark

**Comment by MACscr** [comment]
Just curious what features you are thinking about doing for this new “admin framework” so I can try not to duplicate work on my current project. Not going to hold you to any of it, but you sound passionate like me and like to get stuff knocked out. No matter what, thanks again for your help and what you have put out so far.

**Comment by bastinald** [comment]
going to be adding basic crud to this package soon

maybe 2 versions, with and without filters etc

not sure about tables. they're bad on mobile.

**Comment by bastinald** [comment]
@MACscr  just FYI CRUD has now been added with search sort etc.

https://github.com/bastinald/ui#making-crud
