### ISSUE TITLE
Pivot Tables?

### ISSUE THREAD

**Issue by MACscr** [bastinald/ui#3]
With your migrations design built into the model class, how should pivot tables, etc, be handled? I have Contacts, Vendors, Users, etc, models where I need to be able to relate those to each other. Typically I would have a migrations file/table that would relate them to each other. Wasn't sure if there was a way to handle that when doing the UI migration method within the model class since its really a third table when relating two tables to each other. I know this really isn't any issue, so hopefully its ok to answer here. Probably more a documentation update request? I appreciate your time.

**Comment by bastinald** [comment]
You can either make models for those pivot tables as kind of a placeholder in case you need to perform queries on the pivot tables themselves, or you can use traditional Laravel migrations for them.

This package runs traditional migrations BEFORE the automatic ones, so migration files will work just fine.
