### ISSUE TITLE
Default for Selects and such?

### ISSUE THREAD

**Issue by MACscr** [bastinald/ui#5]
So i have the following setup to give me a nice list of states:

```<x-ui::select :options="App\Models\Contact::states()" label="State" />```

But how do I set a default selected state (Florida for example)? I don't see any default/selected options for selects.

**Comment by bastinald** [comment]
Add a mount() method to your component and inside the mount method:

$this->setData('state', 'Florida')

**Comment by MACscr** [comment]
Got it. No idea why I wasn’t thinking that way originally. Probably because I was trying to use the same component for contact creation and update. Was easy enough to set defaults with an if/then in the component though. Thanks!

- Mark
