### ISSUE TITLE
Feature Request: Component Folders

### ISSUE THREAD

**Issue by MACscr** [bastinald/ui#6]
So as Im testing things and planning, in order to avoid my components and views directory roots from getting messy, it would be nice when creating the component to be able to do something like:

```php artisan ui:component Contacts\create -f```

or something that would automatically put that component into a its own folder. Reason I am asking for this is that each model will have a create, update, and index. Could even have a view if i decide to go that route. Thoughts on this or a better way to keep things organized?

**Comment by bastinald** [comment]
`php artisan ui:component contacts.create --f`

or

`php artisan ui:component Contacts/Create --f`

**Comment by MACscr** [comment]
Ah, i had tried it with Contacts/create, which just created Contactscreate.php. My bad. Thanks!
