### ISSUE TITLE
Can't publish ui stub

### ISSUE THREAD

**Issue by manishlok** [bastinald/ui#8]
Good package to use .
I need to customize login/register form but vendor:publish command fails.
`Can't locate path: <$project_directory\vendor\bastinald\ui\src\Providers/../../views>`
Help Needed !

**Comment by MACscr** [comment]
That’s the error you get when you run the publish command?

- Mark

**Comment by bastinald** [comment]
Did you figure this out? I'm guessing you're on Windows?
